### PR TITLE
Additional methods for the API

### PR DESCRIPTION
**Pull request by JohnMav**
Not sure if you are looking to add this functionality but I found these useful for extracting a users post history from discourse for analysis. 

Added methods to 
 - get users replies with optional offset value
 - get contents of single post by post_id
 - get members of a group
 - create a group

### CODE REVIEW

**Comment by flyeven** [comment]
That's helpful, do you plan to add the "add users to to a group" methods like in the php wraper?

https://github.com/discoursehosting/discourse-api-php/blob/master/lib/DiscourseAPI.php

**Comment by dandv** [comment]
+1 for getting an individual post by id

**Comment by dhyasama** [comment]
Thank you for contributing

**Comment by JohnMav** [comment]
No Problem, glad to contribute back to the project it's been super helpful!

**Pull request merged**
